apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gobank-db
spec:
  instances: 3
  
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  
  bootstrap:
    initdb:
      database: gobank
      owner: root
      secret:
        name: db-creds 

  storage:
    size: 1Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname