apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gobank

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - gobank-api-deployment.yaml
  - service.yaml
  - ingress.yaml